---
# tasks file for roles/filebeat
- name: Create directories for filebeat
  file:
    path: "/tmp/filebeat"
    state: directory
- name: Download filebeat
  copy:
    src: "/etc/ansible/roles/kibana/static/filebeat-8.8.2-amd64.deb"
    dest: /tmp/filebeat
- name: Install filebeat
  apt:
    deb: "/tmp/filebeat/filebeat-8.8.2-amd64.deb"
- name: Copy template
  copy:
    src: "/etc/ansible/roles/filebeat/templates/filebeat.yml"
    dest: /etc/filebeat
- name: Copy module
  copy:
    src: "/etc/ansible/roles/filebeat/templates/nginx.yml"
    dest: /etc/filebeat/modules.d/
- name: Copy ca
  copy:
    src: "/etc/ansible/roles/kibana/static/http_ca.crt"
    dest: /etc/filebeat
